version: '3'

# Declare volumes
volumes:
  nodemodules:
  certs:
  vhost:
  html:
  acme:

# Declare services
services:
  indieweb-express-site:
    build: .
    volumes:
      - ./example/content:/content
      - nodemodules:/usr/src/app/node_modules
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=whalecoiner.localhost
      - VIRTUAL_PORT=3000
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      # - /path/to/certificates:/etc/nginx/certs
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes_from: 
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      # - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=letsencrypt@whalecoiner.com
